import { App, MediaItem, UserAccount } from '@/types';

export const DEFAULT_APPS: App[] = [
  { id: 1,  name: 'Presensi',   url: 'https://s.id/absendigital-smansasih/',       icon: '/logo_presensi.png',    iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 2,  name: 'Peduli',     url: 'https://pedulismansasih.com/',               icon: '/logo_peduli.png',      iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 3,  name: 'Angajih',    url: 'https://angajih-smansasih.vercel.app/',      icon: '/logo_angajih.png',     iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 4,  name: 'Gelis',      url: 'https://gelis-smansasih.vercel.app/',        icon: '/logo_gelis.png',       iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 5,  name: 'Ramadhan',   url: 'https://s.id/smansasih_ramadhan/',           icon: '/logo_ramadhan.png',    iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 6,  name: 'Arsip',      url: '#',                                          icon: '/logo_arsip.png',       iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 7,  name: 'Kantin',     url: '#',                                          icon: '/logo_kantin.png',      iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 8,  name: 'Artificial', url: 'https://ai-smansasih.vercel.app/',           icon: '/logo_artificial.png',  iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 9,  name: 'Asisten',    url: 'https://asistenguru-smansasih.vercel.app/',  icon: '/logo_asisten.png',     iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 10, name: 'Manajemen',  url: '#',                                          icon: '/logo_manajemen.png',   iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 11, name: 'Sispena',    url: 'https://sispena-smansasih.vercel.app/',      icon: '/logo_sispena.png',     iconType: 'image', cat: 'Aplikasi Sekolah' },
  { id: 12, name: 'Kunjungan',  url: 'https://bkd-smansasih.vercel.app/',          icon: '/logo_kunjungan.png',   iconType: 'image', cat: 'Aplikasi Sekolah' },
];

export const MEDIA_ITEMS: MediaItem[] = [
  { name: 'Website',   icon: '🌐', logo: '/logo_website.png',   url: 'https://sman1sumberasih.sch.id/',               desc: 'SMA Negeri 1 Sumberasih' },
  { name: 'Youtube',   icon: '▶️', logo: '/logo_youtube.png',   url: 'https://www.youtube.com/@smanegeri1sumberasih', desc: 'Channel Resmi' },
  { name: 'Instagram', icon: '📸', logo: '/logo_instagram.png', url: 'https://www.instagram.com/smansasih_jaya/',     desc: '@smansasih' },
  { name: 'TikTok',    icon: '🎵', logo: '/logo_tiktok.png',    url: 'https://www.tiktok.com/@osis_smansasih',                                              desc: '@smansasih' },
];

export const EMOJIS = [
  '📊','💰','👥','📋','🗓️','📦','🚚','🏫','📈','💼',
  '🔧','🛒','📝','🌐','📱','🔒','📧','🎯','⚙️','📂',
  '💳','🎓','🔔','📌','🧾','🖨️','📡','🏆','📰','🔑',
  '🤖','📖',
];

export const LOGO_STORAGE_KEYS = {
  'splash-logo': 'smansasih_logo_splash',
  'mascot':      'smansasih_logo_mascot',
  'header-logo': 'smansasih_logo_header',
} as const;

export const APPS_STORAGE_KEY = 'smansasih_v3';

// ── Akun Pengguna ─────────────────────────────────────
// Sistem login:
//   username = tipe role (sama untuk semua pengguna dalam satu tipe)
//   password = nomor identitas unik masing-masing pengguna
//
// Username per role:
//   admin                → "admin"
//   kepala_sekolah       → "kepsek"
//   pendidik             → "guru"    | password = NIP
//   tenaga_administrasi  → "tendik"    | password = NIP
//   siswa                → "siswa"   | password = NISN
//   tamu                 → "tamu"    | password = kode akses


// ── Username per role (dipakai di useUsers & useAuth) ─
export const ROLE_USERNAMES: Record<string, string> = {
  admin:               'admin',
  kepala_sekolah:      'kepsek',
  pendidik:            'guru',
  tenaga_administrasi: 'tendik',
  siswa:               'siswa',
  tamu:                'tamu',
};

export const USERS: UserAccount[] = [
  // ── Admin ─────────────────────────────────────────
  { username: 'admin',  password: 'adminsmansasih',      name: 'Administrator',          role: 'admin',               avatar: '🛡️' },

  // ── Kepala Sekolah (password = NIP) ───────────────
  { username: 'kepsek', password: '197702142010011013',  name: 'Muhlas Fauzi, S.Pd., M.Pd',   role: 'kepala_sekolah',      avatar: '👨‍💼' },

  // ── Pendidik / Guru (password = NIP) — 17 guru ─────────────
  { username: 'guru', password: '1234567890', name: 'Abdur Rahman Rizqi', role: 'pendidik', avatar: '👨‍🏫' },
  { username: 'guru', password: '199501092025212024', name: 'Ayu Ilmiah', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '3513216804970001', name: 'Devi Damaianti', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '198610162022212021', name: 'Dewi Suprobo Rini', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '198402102011011007', name: 'Fathur Rakhman', role: 'pendidik', avatar: '👨‍🏫' },
  { username: 'guru', password: '198812292025212038', name: 'Fatimah', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '198412062022212030', name: 'Herni Lindawati', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '198806052022212020', name: 'Hesti Lestia Wulandari', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '198505072011012010', name: 'Lina Rachmawati', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '198206032022211014', name: 'Made Malvinas Primadona', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '198405232022211011', name: 'Moch. Fariet Catur Anggun Basony', role: 'pendidik', avatar: '👨‍🏫' },
  { username: 'guru', password: '198604302022211016', name: 'Muhammad Usamah Rasyidi', role: 'pendidik', avatar: '👨‍🏫' },
  { username: 'guru', password: '198111262009032002', name: 'Novi Mudhofiroh', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '198401282024212014', name: 'Nurwati', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '197601012007012043', name: 'Sri Yunati', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '197304152011012001', name: 'Sucik Ambarwati', role: 'pendidik', avatar: '👩‍🏫' },
  { username: 'guru', password: '199101012019032018', name: 'Ujik Rachmatul Hijriyah', role: 'pendidik', avatar: '👩‍🏫' },

  // ── Tenaga Administrasi (password = NIP/NRK) ──────
  { username: 'tendik',   password: '199406302025041000',  name: 'Ilmi Firmansayh',        role: 'tenaga_administrasi', avatar: '👩‍💻' },
  { username: 'tendik',   password: '199205202019031005',  name: 'Rian Hidayat',           role: 'tenaga_administrasi', avatar: '👨‍💻' },

  // ── Siswa (password = NISN) — 187 siswa ────────────────
  { username: 'siswa',  password: '2026794',  name: 'A. Zidan Ramdani',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026824',  name: 'Achmad Zainal Abidin',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026826',  name: 'Ahmad Dhani',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026795',  name: 'Ahmad Fauzi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026853',  name: 'Arista Mauludiyah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026797',  name: 'Aulia Titian Islamiah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026799',  name: 'Haidar Ali',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026801',  name: 'Hudayrobi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026837',  name: 'M. Rofiqi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026804',  name: 'Muhammad Abdi Maulana',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026805',  name: 'Muhammad Fahris Rozikin',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026842',  name: 'Muhammad Kamil',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026807',  name: 'Muhammad Ridwan',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026808',  name: 'Nina Afkarina',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026809',  name: 'Nur Aini',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026811',  name: 'Nurany Yunita Hikmah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026812',  name: 'Ramadani Nur Fitria',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026813',  name: 'Reva Dwita Herfiani',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026858',  name: 'Revalina Aprilia',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026814',  name: 'Riskahati Wau',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026815',  name: 'Riski Yanto',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026854',  name: 'Rosa Nala Syarofah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026855',  name: 'Sa\'Aban Ramadan',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026817',  name: 'Silfiatun Ilmiah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026819',  name: 'Sohibul Anwar',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026820',  name: 'Sudiqul Huluqi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026821',  name: 'Syafiuddin',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026822',  name: 'Syarifatul Afiah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026825',  name: 'Afan Fadli',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026857',  name: 'Ahmad Albi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026827',  name: 'Ahmad Fendy',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026828',  name: 'Ainur Rohman',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026829',  name: 'Andrik Mandala Putra',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026796',  name: 'Anggaraini',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026852',  name: 'Arina Rahmatika',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026830',  name: 'Dela Octavia',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026831',  name: 'Farid',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026800',  name: 'Hasan Afini Maulana',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026802',  name: 'Irza Hayatun Nufus',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026803',  name: 'Isaim Khoir',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026767',  name: 'Khidir Mustofa',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026833',  name: 'Kuntum Fiamanillah Maula R',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026834',  name: 'Laila Savira Pebriyanti',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026835',  name: 'Lilis',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026836',  name: 'M. Bayu Firmanshah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026838',  name: 'Masrohil',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026839',  name: 'Misbahul Munir',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026840',  name: 'Muhammad Abdul Muhyi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026841',  name: 'Muhammad Fatahillah',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026806',  name: 'Muhammad Lutfi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026843',  name: 'Nabil Barrih',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026844',  name: 'Nayla',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026810',  name: 'Nur Fitria',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026845',  name: 'Rizkazir Ramadhani',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026846',  name: 'Rohman Hakim',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026847',  name: 'Sahron',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026816',  name: 'Saroh',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026849',  name: 'Siti Nur Aisyah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026818',  name: 'Siti Romla',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026850',  name: 'Sofyan',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026851',  name: 'Tuti Syirfatul Aisyah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026823',  name: 'Zahwa Rukilatul Jannah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026736',  name: 'A. Dika Zainul Millah',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026633',  name: 'A. Miftahul Huda',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026634',  name: 'Abdul Malik',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026682',  name: 'Angelin Maulidiah Mareta Gopare',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026764',  name: 'Fahmi Akbar',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026765',  name: 'Farid Gofur',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026685',  name: 'Firdaus',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026695',  name: 'Ghazali Adi Rismawan',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026670',  name: 'Ibnu Hajar',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026698',  name: 'Is\'adur Rofiq',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026697',  name: 'Laily Rafika',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026677',  name: 'Lailyatul Munawaroh',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026693',  name: 'Lukman',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026686',  name: 'M. Dimas Adipura',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026783',  name: 'Maskur Huda',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026769',  name: 'Muhammad Firdaus',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026700',  name: 'Muhammad Ikbal',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026701',  name: 'Muhammad Rendi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026706',  name: 'Muhammad Rofiqul Anwar',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026785',  name: 'Muhammad Zainul Akbar',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026704',  name: 'Nur Aini Putriningtias',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026712',  name: 'Nur Kholifah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026710',  name: 'Ravi Ahnaf Alarice',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026719',  name: 'Umrotul Azizah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026787',  name: 'Widyan Salsabila Arwanaura',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026717',  name: 'Wildani Lubi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026721',  name: 'Yeni Cantika Sari',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026788',  name: 'Ahmad Wahid',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026666',  name: 'Ahmad Wildan',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026683',  name: 'Ainun Nadzifah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026679',  name: 'Aminatuzzuhriyah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026689',  name: 'Emi Puji Wulandari',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026692',  name: 'Farel Zainal Abidin',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026668',  name: 'Finsaatur Robi\'Ah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026688',  name: 'Ibnu Athoillah',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026691',  name: 'Johan',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026694',  name: 'Kurnia Duwi Rahayu',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026792',  name: 'Levi Nur Aini',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026737',  name: 'Lutfiatul Karomah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026768',  name: 'M. Fathor Rozi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026789',  name: 'Maisa',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026702',  name: 'Masrur Robittullah',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026699',  name: 'Mita',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026703',  name: 'Mohammad Nuril Hadisi Ali Alatas',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026705',  name: 'Muhammad Bahron',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026709',  name: 'Muhammad Umar Said',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026707',  name: 'Nur Halimah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026729',  name: 'Oktafiatur Ramadani',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026713',  name: 'Radit',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026731',  name: 'Rizqi',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026770',  name: 'Rosa',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026716',  name: 'Rosalinda',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026715',  name: 'Saifu Deni Mofich',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026718',  name: 'Silfianatul Ulfa',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026732',  name: 'Urifa Alkarina',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026773',  name: 'Abdul Roszek',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026774',  name: 'Afdilul Akbar',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026681',  name: 'Ainul Yaqin',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026775',  name: 'Andika Maulana',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026776',  name: 'Andini Aulia Putri',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026734',  name: 'Ardatus Sairoh',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026684',  name: 'Dian Eka Lestari',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026735',  name: 'Dian Febriyanti Putri',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026730',  name: 'Fadhur Rosi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026727',  name: 'Fahmi Ilham',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026777',  name: 'Firdatul Hasanah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026778',  name: 'Hamada Sahrullah',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026687',  name: 'Hasbi Ullah',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026724',  name: 'Hoirun Anisa',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026779',  name: 'Illiyah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026690',  name: 'Karimatus Salsabila',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026726',  name: 'Lukman Hakim',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026781',  name: 'Lukmanul Hakim',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026782',  name: 'M. Yazit Albustomi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026696',  name: 'Mamluatul Khoiriyah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026711',  name: 'Moh. Risqi Wahyudi',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026784',  name: 'Moh. Sikin',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026733',  name: 'Muhammad Shohil',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026728',  name: 'Nadin Ardila Nafisah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026708',  name: 'Nasihin Nasih',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026791',  name: 'Nora Fahria',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026856',  name: 'Rifalun Umam',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026786',  name: 'Siti Khoir',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026714',  name: 'Siti Khotijah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026725',  name: 'Syarifah Ummus Salamah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026793',  name: 'Unziatus Zahroh',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026720',  name: 'Yulinda',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026723',  name: 'Zuber',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026637',  name: 'Airim Sakurah Mawati',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026659',  name: 'Aliatun Rofiah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026639',  name: 'Aril Mediansyah',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026664',  name: 'Faiyil Adam',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026611',  name: 'Guruh Fajar Dwi Putra',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026667',  name: 'Heri Kurniawan',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026643',  name: 'Jhovin Akbar',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026644',  name: 'Khoirul Anam',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026630',  name: 'Muchammad Alwey',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026648',  name: 'Muhammad Andrian',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026649',  name: 'Muhammad Imam Sibaweh',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026671',  name: 'Muhammad Rojil Gufron',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026632',  name: 'Puput Indriyani',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026672',  name: 'Rani Dwi Febriyanti',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026673',  name: 'Rojil Ghufron',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026676',  name: 'Siti Nadiyatul Jannah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026655',  name: 'Susi',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026658',  name: 'Zery Hidayat',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026635',  name: 'Abd. Rohman',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026636',  name: 'Ahmad Sugianto',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026660',  name: 'Ayu Mukaromah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026662',  name: 'Dimas Adi Putra',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026640',  name: 'Holila Aprilia',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026642',  name: 'Jamilatul Firdaus',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026645',  name: 'M. Faisal Amri',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026610',  name: 'Mahrus Ramadani',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026646',  name: 'Moch. Firdaus',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026647',  name: 'Mohammad Nasih',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026651',  name: 'Nurul Laili',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026674',  name: 'Silvia',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026675',  name: 'Sinta Nur Aini',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026653',  name: 'Siti Fatimah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026654',  name: 'Siti Nur Azizah',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026678',  name: 'Syahrul',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026656',  name: 'Umar Hamdan',  role: 'siswa', avatar: '👦' },
  { username: 'siswa',  password: '2026657',  name: 'Vina Dwi Umroh',  role: 'siswa', avatar: '👧' },
  { username: 'siswa',  password: '2026790',  name: 'Zummari Ahmad Wiraraja Al Bukhari',  role: 'siswa', avatar: '👦' },

  // ── Tamu (password = kode akses) ─────────────────
  { username: 'tamu',   password: 'tamu',                name: 'Tamu',                   role: 'tamu',                avatar: '👤' },
];